name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write  # Needed to create PRs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install && git config user.name "GitHub Actions" && git config user.email "actions@github.com"
      - name: Commit lockfile if changed
        run: |
          if git diff --exit-code package-lock.json; then
            echo "No changes to package-lock.json"
          else
            git add package-lock.json
            git commit -m "chore: update lockfile [skip ci]"
            git push
          fi

      - name: Build all packages
        run: npm run build:all
      
      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          # This script runs ONLY when publishing (Phase 2)
          publish: npm run release
          createGithubReleases: true
          # This script runs ONLY when creating version PR (Phase 1)
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
